version: 2

jobs:
  build:
    working_directory: ~/instagram-shortcut-extension
    docker:
      - image: circleci/node:10.15.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependency
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Packaging
          command: npm run package
      - run:
          name: Unit Test
          environment:
            JEST_JUNIT_OUTPUT: 'test-results/junit/js-unit-test-results.xml'
          command: npm t -- --ci --coverage --reporters=default --reporters=jest-junit
      - store_test_results:
          path: test-results
      - run:
          name: E2E Test
          command: npm run e2e
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: out
      - store_artifacts:
          path: coverage

  deploy:
    working_directory: ~/instagram-shortcut-extension
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - deploy:
          command: |
            cd workspace
            npm run release:cws

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
